# Dockerfile.dev (DEV)
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Копируем оба файла с зависимостями
COPY requirements.txt requirements.dev.txt /app/

# Ставим dev-зависимости (внутри есть -r requirements.txt)
RUN pip install --no-cache-dir -r requirements.dev.txt

# Копируем весь проект (но код всё равно перекроем volume-ом в dev-compose)
COPY . /app/

# Переключаемся в backend, где manage.py
WORKDIR /app/backend

CMD ["bash", "-c", "python manage.py runserver 0.0.0.0:8000"]
