# Generated by Django 4.2.16 on 2025-12-08 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("BUSINESS", "Business"),
                        ],
                        default="INDIVIDUAL",
                        help_text="Тип получателя: физлицо или бизнес.",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Имя/ФИО или название компании.", max_length=255
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        help_text="Номер карты/счёта/IBAN в исходном виде.",
                        max_length=64,
                    ),
                ),
                (
                    "bank_code",
                    models.CharField(
                        blank=True,
                        help_text="Идентификатор банка (MFO/BIC/SWIFT и т.п.), если применимо.",
                        max_length=32,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Код страны (ISO 3166-1 alpha-2), например: UA, US, PL.",
                        max_length=2,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Можно ли сейчас использовать получателя для новых выплат.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Когда получатель был создан."
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Когда получатель был изменён в последний раз.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель выплаты",
                "verbose_name_plural": "Получатели выплат",
                "db_table": "payouts_recipient",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idempotency_key",
                    models.CharField(
                        help_text="Ключ для идемпотентного создания выплаты.",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Сумма выплаты.", max_digits=12
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="Код валюты (ISO 4217, например: USD, EUR, UAH).",
                        max_length=3,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="NEW",
                        help_text="Текущий статус заявки.",
                        max_length=20,
                    ),
                ),
                (
                    "recipient_name_snapshot",
                    models.CharField(
                        help_text="Имя/ФИО/название получателя на момент создания выплаты.",
                        max_length=255,
                    ),
                ),
                (
                    "account_number_snapshot",
                    models.CharField(
                        help_text="Номер карты/счёта получателя на момент создания выплаты.",
                        max_length=64,
                    ),
                ),
                (
                    "bank_code_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Банковский идентификатор на момент создания выплаты.",
                        max_length=32,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Когда заявка была создана.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Когда заявка была изменена в последний раз.",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Получатель, которому отправляем деньги.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="payouts.recipient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на выплату",
                "verbose_name_plural": "Заявки на выплату",
                "db_table": "payouts_payout",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="payouts_pay_status_dd1f82_idx",
                    ),
                    models.Index(
                        fields=["recipient", "created_at"],
                        name="payouts_pay_recipie_98e0df_idx",
                    ),
                ],
            },
        ),
    ]
